/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-2-7:  4h:35m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_type(atstype_ptrk) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(malloc)
ATSdyncst_mac(ward_ptr_add)
ATSdyncst_mac(atspre_g1uint2int_size_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
/*
/opt/homedir/src/ward/memory.dats: 270(line=10, offs=3) -- 298(line=10, offs=31)
*/
ATSassume(_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_own) ;
/*
/opt/homedir/src/ward/memory.dats: 301(line=11, offs=3) -- 335(line=11, offs=37)
*/
ATSassume(_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_frozen) ;
/*
/opt/homedir/src/ward/memory.dats: 338(line=12, offs=3) -- 369(line=12, offs=34)
*/
ATSassume(_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow) ;
/*
/opt/homedir/src/ward/memory.dats: 372(line=13, offs=3) -- 400(line=13, offs=31)
*/
ATSassume(_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr) ;
/*
/opt/homedir/src/ward/memory.dats: 403(line=14, offs=3) -- 441(line=14, offs=41)
*/
ATSassume(_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_frozen) ;
/*
/opt/homedir/src/ward/memory.dats: 444(line=15, offs=3) -- 479(line=15, offs=38)
*/
ATSassume(_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow) ;
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__sized_malloc(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__sized_free(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_ptr(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
postiats_tyrec_0
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_advance(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_rejoin(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__safe_memset(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__safe_memcpy(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
postiats_tyrec_0
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_freeze(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_clone(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_return(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_thaw(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_read(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
ATSLIB_056_prelude_056_unsafe__ptr0_get__12(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude_056_unsafe__ptr0_get__12__1(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_ptr(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_init__15(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_get__16(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_set__17(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_dissolve__18(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_ptr__19(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
postiats_tyrec_0
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_freeze__20(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_get__21(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_clone__22(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_return__23(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_thaw__24(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_getptr__25(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

/*
/opt/homedir/src/ward/memory.dats: 835(line=26, offs=26) -- 855(line=26, offs=46)
*/
/*
local: 
global: sized_malloc$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__sized_malloc(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 820(line=26, offs=11) -- 856(line=26, offs=47)
*/
ATSINSflab(__patsflab_sized_malloc):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 841(line=26, offs=32) -- 855(line=26, offs=46)
*/
ATSINSmove(tmpret0, malloc(arg0)) ;

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__sized_malloc] */

/*
/opt/homedir/src/ward/memory.dats: 884(line=28, offs=27) -- 920(line=29, offs=30)
*/
/*
local: 
global: sized_free$1$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__sized_free(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 868(line=28, offs=11) -- 920(line=29, offs=30)
*/
ATSINSflab(__patsflab_sized_free):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 893(line=29, offs=3) -- 920(line=29, offs=30)
*/
ATSINSmove_void(tmpret1, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__sized_free] */

/*
/opt/homedir/src/ward/memory.dats: 945(line=31, offs=24) -- 954(line=31, offs=33)
*/
/*
local: 
global: raw_ptr$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_ptr(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 932(line=31, offs=11) -- 954(line=31, offs=33)
*/
ATSINSflab(__patsflab_raw_ptr):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 952(line=31, offs=31) -- 954(line=31, offs=33)
*/
ATSINSmove(tmpret2, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_ptr] */

/*
/opt/homedir/src/ward/memory.dats: 985(line=33, offs=30) -- 1067(line=37, offs=4)
*/
/*
local: 
global: raw_advance$3$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_advance(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, postiats_tyrec_0) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 966(line=33, offs=11) -- 1067(line=37, offs=4)
*/
ATSINSflab(__patsflab_raw_advance):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1000(line=33, offs=45) -- 1067(line=37, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1019(line=34, offs=16) -- 1044(line=34, offs=41)
*/
ATSINSmove(tmp4, ward_ptr_add(arg0, arg1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1050(line=36, offs=3) -- 1063(line=36, offs=16)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret3, postiats_tyrec_0, atslab__0, arg0) ;
ATSINSstore_fltrec_ofs(tmpret3, postiats_tyrec_0, atslab__1, tmp4) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1000(line=33, offs=45) -- 1067(line=37, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_advance] */

/*
/opt/homedir/src/ward/memory.dats: 1097(line=39, offs=29) -- 1117(line=39, offs=49)
*/
/*
local: 
global: raw_rejoin$4$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_rejoin(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1079(line=39, offs=11) -- 1117(line=39, offs=49)
*/
ATSINSflab(__patsflab_raw_rejoin):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1113(line=39, offs=45) -- 1117(line=39, offs=49)
*/
ATSINSmove(tmpret5, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_rejoin] */

/*
/opt/homedir/src/ward/memory.dats: 1150(line=41, offs=32) -- 1202(line=42, offs=37)
*/
/*
local: 
global: safe_memset$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__safe_memset(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1129(line=41, offs=11) -- 1202(line=42, offs=37)
*/
ATSINSflab(__patsflab_safe_memset):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1168(line=42, offs=3) -- 1202(line=42, offs=37)
*/
ATSINSmove_void(tmpret6, ATSextfcall(memset, (arg1, arg2, arg3))) ;
ATSfunbody_end()
ATSreturn_void(tmpret6) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__safe_memset] */

/*
/opt/homedir/src/ward/memory.dats: 1248(line=45, offs=3) -- 1320(line=46, offs=41)
*/
/*
local: 
global: safe_memcpy$6$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__safe_memcpy(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1, atstkind_type(atstype_ptrk) arg2, atstkind_type(atstype_ptrk) arg3, atstkind_t0ype(atstype_int) arg4)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret7) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1214(line=44, offs=11) -- 1320(line=46, offs=41)
*/
ATSINSflab(__patsflab_safe_memcpy):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1282(line=46, offs=3) -- 1320(line=46, offs=41)
*/
ATSINSmove_void(tmpret7, ATSextfcall(memcpy, (arg2, arg3, arg4))) ;
ATSfunbody_end()
ATSreturn_void(tmpret7) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__safe_memcpy] */

/*
/opt/homedir/src/ward/memory.dats: 1348(line=48, offs=27) -- 1364(line=48, offs=43)
*/
/*
local: 
global: raw_freeze$7$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_freeze(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1332(line=48, offs=11) -- 1364(line=48, offs=43)
*/
ATSINSflab(__patsflab_raw_freeze):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1355(line=48, offs=34) -- 1364(line=48, offs=43)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret8, postiats_tyrec_0, atslab__0, arg0) ;
ATSINSstore_fltrec_ofs(tmpret8, postiats_tyrec_0, atslab__1, arg0) ;
ATSINSmove_fltrec_end()
ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_freeze] */

/*
/opt/homedir/src/ward/memory.dats: 1401(line=50, offs=36) -- 1426(line=50, offs=61)
*/
/*
local: 
global: raw_borrow_clone$8$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_clone(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1376(line=50, offs=11) -- 1426(line=50, offs=61)
*/
ATSINSflab(__patsflab_raw_borrow_clone):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1420(line=50, offs=55) -- 1426(line=50, offs=61)
*/
ATSINSmove(tmpret9, arg1) ;
ATSfunbody_end()
ATSreturn(tmpret9) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_clone] */

/*
/opt/homedir/src/ward/memory.dats: 1464(line=52, offs=37) -- 1485(line=52, offs=58)
*/
/*
local: 
global: raw_borrow_return$9$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_return(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret10) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1438(line=52, offs=11) -- 1485(line=52, offs=58)
*/
ATSINSflab(__patsflab_raw_borrow_return):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1483(line=52, offs=56) -- 1485(line=52, offs=58)
*/
ATSINSmove_void(tmpret10, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret10) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_return] */

/*
/opt/homedir/src/ward/memory.dats: 1511(line=54, offs=25) -- 1528(line=54, offs=42)
*/
/*
local: 
global: raw_thaw$10$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_thaw(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1497(line=54, offs=11) -- 1528(line=54, offs=42)
*/
ATSINSflab(__patsflab_raw_thaw):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1522(line=54, offs=36) -- 1528(line=54, offs=42)
*/
ATSINSmove(tmpret11, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_thaw] */

/*
/opt/homedir/src/ward/memory.dats: 1564(line=56, offs=35) -- 1625(line=57, offs=45)
*/
/*
local: 
global: raw_borrow_read$11$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_read(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1540(line=56, offs=11) -- 1625(line=57, offs=45)
*/
ATSINSflab(__patsflab_raw_borrow_read):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1605(line=57, offs=25) -- 1624(line=57, offs=44)
*/
ATSINSmove(tmp15, ward_ptr_add(arg1, arg2)) ;

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1583(line=57, offs=3) -- 1625(line=57, offs=45)
*/
ATSINSmove(tmpret12, ATSLIB_056_prelude_056_unsafe__ptr0_get__12__1(tmp15)) ;

ATSfunbody_end()
ATSreturn(tmpret12) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_read] */

#if(0)
/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1763(line=60, offs=3) -- 1976(line=68, offs=2)
*/
/*
local: 
global: ptr0_get$12$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(5723)
tmparg = S2Evar(a(5723))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056_prelude_056_unsafe__ptr0_get__12(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1752(line=59, offs=1) -- 1976(line=68, offs=2)
*/
ATSINSflab(__patsflab_ptr0_get):
/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1950(line=66, offs=11) -- 1952(line=66, offs=13)
*/
ATSINSmove(tmpret13, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret13) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_get__12] */
#endif // end of [TEMPLATE]

/*
/opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1763(line=60, offs=3) -- 1976(line=68, offs=2)
*/
/*
local: 
global: ptr0_get$12$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5723)
tmparg = S2Evar(a(5723))
tmpsub = Some(a(5723) -> S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int)))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude_056_unsafe__ptr0_get__12__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1752(line=59, offs=1) -- 1976(line=68, offs=2)
*/
ATSINSflab(__patsflab_ptr0_get):
/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1950(line=66, offs=11) -- 1952(line=66, offs=13)
*/
ATSINSmove(tmpret13__1, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_int))) ;
/*
emit_instr: loc0 = /opt/homedir/.ats2/ATS2-Postiats-int-0.4.2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret13__1) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_get__12__1] */

/*
/opt/homedir/src/ward/memory.dats: 1657(line=59, offs=31) -- 1674(line=59, offs=48)
*/
/*
local: 
global: raw_borrow_ptr$14$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_ptr(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1637(line=59, offs=11) -- 1674(line=59, offs=48)
*/
ATSINSflab(__patsflab_raw_borrow_ptr):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1668(line=59, offs=42) -- 1674(line=59, offs=48)
*/
ATSINSmove(tmpret16, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__raw_borrow_ptr] */

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 1872(line=66, offs=22) -- 1986(line=71, offs=4)
*/
/*
local: 
global: tptr_init$15$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8685)
tmparg = S2Evar(a(8685))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_init__15(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp20) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1851(line=66, offs=1) -- 1986(line=71, offs=4)
*/
ATSINSflab(__patsflab_tptr_init):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1885(line=66, offs=35) -- 1986(line=71, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1908(line=67, offs=20) -- 1923(line=67, offs=35)
*/
ATSINSmove(tmp19, atspre_g1uint2int_size_int(ATSPMVsizeof(atstyvar_type(a)))) ;

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1904(line=67, offs=16) -- 1923(line=67, offs=35)
*/
ATSINSmove(tmp18, PMVtmpltcst(g1int_mul<S2Eextkind(atstype_int)>)(arg2, tmp19)) ;

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1935(line=68, offs=12) -- 1974(line=68, offs=51)
*/
ATSINSmove_void(tmp20, ATSextfcall(memset, (arg1, ATSPMVi0nt(0), tmp18))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1980(line=70, offs=3) -- 1982(line=70, offs=5)
*/
ATSINSmove(tmpret17, arg0) ;
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 1885(line=66, offs=35) -- 1986(line=71, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret17) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_init__15] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2017(line=74, offs=17) -- 2069(line=75, offs=40)
*/
/*
local: 
global: tptr_get$16$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8694)
tmparg = S2Evar(a(8694))
tmpsub = None()
*/
atstyvar_type(a)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_get__16(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21, atstyvar_type(a)) ;
ATStmpdec(tmp22, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2001(line=74, offs=1) -- 2069(line=75, offs=40)
*/
ATSINSflab(__patsflab_tptr_get):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2052(line=75, offs=23) -- 2068(line=75, offs=39)
*/
ATSINSmove(tmp22, PMVtmpltcst(ptr1_add_gint<S2Evar(a(8694))><S2Eextkind(atstype_int)>)(arg1, arg2)) ;

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2032(line=75, offs=3) -- 2069(line=75, offs=40)
*/
ATSINSmove(tmpret21, PMVtmpltcst(ptr0_get<S2Evar(a(8694))>)(tmp22)) ;

ATSfunbody_end()
ATSreturn(tmpret21) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_get__16] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2100(line=78, offs=17) -- 2158(line=79, offs=43)
*/
/*
local: 
global: tptr_set$17$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8703)
tmparg = S2Evar(a(8703))
tmpsub = None()
*/
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_set__17(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2, atstyvar_type(a) arg3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret23) ;
ATStmpdec(tmp24, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2084(line=78, offs=1) -- 2158(line=79, offs=43)
*/
ATSINSflab(__patsflab_tptr_set):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2138(line=79, offs=23) -- 2154(line=79, offs=39)
*/
ATSINSmove(tmp24, PMVtmpltcst(ptr1_add_gint<S2Evar(a(8703))><S2Eextkind(atstype_int)>)(arg1, arg2)) ;

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2118(line=79, offs=3) -- 2158(line=79, offs=43)
*/
ATSINSmove_void(tmpret23, PMVtmpltcst(ptr0_set<S2Evar(a(8703))>)(tmp24, arg3)) ;

ATSfunbody_end()
ATSreturn_void(tmpret23) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_set__17] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2192(line=82, offs=20) -- 2201(line=82, offs=29)
*/
/*
local: 
global: tptr_dissolve$18$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8712)
tmparg = S2Evar(a(8712))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_dissolve__18(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2173(line=82, offs=1) -- 2201(line=82, offs=29)
*/
ATSINSflab(__patsflab_tptr_dissolve):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2199(line=82, offs=27) -- 2201(line=82, offs=29)
*/
ATSINSmove(tmpret25, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret25) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_dissolve__18] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2230(line=85, offs=15) -- 2239(line=85, offs=24)
*/
/*
local: 
global: tptr_ptr$19$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8718)
tmparg = S2Evar(a(8718))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_ptr__19(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2216(line=85, offs=1) -- 2239(line=85, offs=24)
*/
ATSINSflab(__patsflab_tptr_ptr):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2237(line=85, offs=22) -- 2239(line=85, offs=24)
*/
ATSINSmove(tmpret26, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret26) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_ptr__19] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2271(line=88, offs=18) -- 2287(line=88, offs=34)
*/
/*
local: 
global: tptr_freeze$20$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8724)
tmparg = S2Evar(a(8724))
tmpsub = None()
*/
postiats_tyrec_0
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_freeze__20(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2254(line=88, offs=1) -- 2287(line=88, offs=34)
*/
ATSINSflab(__patsflab_tptr_freeze):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2278(line=88, offs=25) -- 2287(line=88, offs=34)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret27, postiats_tyrec_0, atslab__0, arg0) ;
ATSINSstore_fltrec_ofs(tmpret27, postiats_tyrec_0, atslab__1, arg0) ;
ATSINSmove_fltrec_end()
ATSfunbody_end()
ATSreturn(tmpret27) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_freeze__20] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2325(line=91, offs=24) -- 2381(line=92, offs=40)
*/
/*
local: 
global: tptr_borrow_get$21$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8730)
tmparg = S2Evar(a(8730))
tmpsub = None()
*/
atstyvar_type(a)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_get__21(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret28, atstyvar_type(a)) ;
ATStmpdec(tmp29, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2302(line=91, offs=1) -- 2381(line=92, offs=40)
*/
ATSINSflab(__patsflab_tptr_borrow_get):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2364(line=92, offs=23) -- 2380(line=92, offs=39)
*/
ATSINSmove(tmp29, PMVtmpltcst(ptr1_add_gint<S2Evar(a(8730))><S2Eextkind(atstype_int)>)(arg1, arg2)) ;

/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2344(line=92, offs=3) -- 2381(line=92, offs=40)
*/
ATSINSmove(tmpret28, PMVtmpltcst(ptr0_get<S2Evar(a(8730))>)(tmp29)) ;

ATSfunbody_end()
ATSreturn(tmpret28) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_get__21] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2422(line=95, offs=27) -- 2447(line=95, offs=52)
*/
/*
local: 
global: tptr_borrow_clone$22$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8739)
tmparg = S2Evar(a(8739))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_clone__22(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2396(line=95, offs=1) -- 2447(line=95, offs=52)
*/
ATSINSflab(__patsflab_tptr_borrow_clone):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2441(line=95, offs=46) -- 2447(line=95, offs=52)
*/
ATSINSmove(tmpret30, arg1) ;
ATSfunbody_end()
ATSreturn(tmpret30) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_clone__22] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2489(line=98, offs=28) -- 2510(line=98, offs=49)
*/
/*
local: 
global: tptr_borrow_return$23$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8749)
tmparg = S2Evar(a(8749))
tmpsub = None()
*/
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_return__23(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret31) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2462(line=98, offs=1) -- 2510(line=98, offs=49)
*/
ATSINSflab(__patsflab_tptr_borrow_return):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2508(line=98, offs=47) -- 2510(line=98, offs=49)
*/
ATSINSmove_void(tmpret31, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret31) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_return__23] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2540(line=101, offs=16) -- 2557(line=101, offs=33)
*/
/*
local: 
global: tptr_thaw$24$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8759)
tmparg = S2Evar(a(8759))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_thaw__24(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret32, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2525(line=101, offs=1) -- 2557(line=101, offs=33)
*/
ATSINSflab(__patsflab_tptr_thaw):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2551(line=101, offs=27) -- 2557(line=101, offs=33)
*/
ATSINSmove(tmpret32, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret32) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_thaw__24] */
#endif // end of [TEMPLATE]

#if(0)
/*
/opt/homedir/src/ward/memory.dats: 2596(line=104, offs=25) -- 2613(line=104, offs=42)
*/
/*
local: 
global: tptr_borrow_getptr$25$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8765)
tmparg = S2Evar(a(8765))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_getptr__25(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret33, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2572(line=104, offs=1) -- 2613(line=104, offs=42)
*/
ATSINSflab(__patsflab_tptr_borrow_getptr):
/*
emit_instr: loc0 = /opt/homedir/src/ward/memory.dats: 2607(line=104, offs=36) -- 2613(line=104, offs=42)
*/
ATSINSmove(tmpret33, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret33) ;
} /* end of [_057_opt_057_homedir_057_src_057_ward_057_memory_056_sats__tptr_borrow_getptr__25] */
#endif // end of [TEMPLATE]

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_opt_057_homedir_057_src_057_ward_057_memory_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_opt_057_homedir_057_src_057_ward_057_memory_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_opt_057_homedir_057_src_057_ward_057_memory_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_opt_057_homedir_057_src_057_ward_057_memory_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
